AT-2 Initial commit
YehorKorotun/Task2 pull request #1
Opened 2020-10-29 15:41 UTC by YehorKorotun

2020-11-03 20:59 UTC, AliceIgorevna requested changes
I cannot see this part of task:
`Define for each class which characteristics may belong to the class. Define for each class which behaviour is belonging to the class. Implement the logic outlined above for each class.`

2020-11-03 20:59 UTC, AliceIgorevna commented on src/main/java/Human.java
> +    }
It also could be toString() method overriding

2020-11-03 20:59 UTC, AliceIgorevna commented on src/main/java/Men.java
> +    }
in this case you could use:
super.giveInformation(); + add new about drink (because currently this overriding makes no sense) but, keep in mind, that it would be better to use 'this' as a reference to the current object in the parent method, like: 
...
System.out.println("Full name is : " + this.fullName);
...

2020-11-03 20:59 UTC, AliceIgorevna commented on src/main/java/Women.java
> +    }
same as above

2020-11-04 20:40 UTC, YehorKorotun commented on src/main/java/Human.java
> +    }
Modified

2020-11-04 20:40 UTC, YehorKorotun commented on src/main/java/Men.java
> +    }
got it

2020-11-04 20:40 UTC, YehorKorotun commented on src/main/java/Women.java
> +    }
Modified

2020-11-05 00:08 UTC, YehorKorotun commented
> I cannot see this part of task:
> `Define for each class which characteristics may belong to the class. Define for each class which behaviour is belonging to the class. Implement the logic outlined above for each class.`

I got it, but I have different methods, in case for man is drink rather women is cocktail. Add the different characteristics.

2020-11-15 15:37 UTC, AliceIgorevna approved these changes

2020-11-15 15:37 UTC, AliceIgorevna commented on src/main/java/Women.java
> +    static void getFavoriteSong() {
why not public?

2020-11-15 15:37 UTC, AliceIgorevna commented on src/main/java/Men.java
> +    static void getFavoriteGame(){
why not public?

2020-11-16 21:08 UTC, merged