AT-3 Merge to master
YehorKorotun/Task2 pull request #2
Opened 2020-10-31 15:31 UTC by YehorKorotun

2020-11-03 21:35 UTC, AliceIgorevna requested changes
All this comments can be discussed by voice.
Take into account all my comments and ask questions in case of any misunderstanding

2020-11-03 21:35 UTC, AliceIgorevna commented on src/main/java/calculatorCalories/Vegetable.java
> +        if (weight != other.weight){return false;}
two vegetables of one type could have different weight in real life, Think about that.

2020-11-03 21:35 UTC, AliceIgorevna commented on src/main/java/calculatorCalories/Vegetable.java
> +public class Vegetable {
Generally this class is ok

2020-11-03 21:35 UTC, AliceIgorevna commented on src/main/java/calculatorCalories/Tomato.java
> +    }
what if I would like to put into salad not 150 grams of tomato but more/less? what should I do?

2020-11-03 21:35 UTC, AliceIgorevna commented on src/main/java/calculatorCalories/Pepper.java
> +    }
what if I would like to put into salad not 150 grams of pepper but more/less? what should I do?

2020-11-03 21:35 UTC, AliceIgorevna commented on src/main/java/calculatorCalories/Onion.java
> +    }
what if I would like to put into salad not 200 grams of pepper but more/less? what should I do?

2020-11-03 21:35 UTC, AliceIgorevna commented on src/main/java/calculatorCalories/Cucumbers.java
> +    }
what if I would like to put into salad not 230 grams of Cucumber but more/less? what should I do?

2020-11-03 21:35 UTC, AliceIgorevna commented on src/main/java/calculatorCalories/Chief.java
> +//    }
consider `Calories calculator` as Chief util. So in your demo class you would get smth like:
CalculatingCalories. calculateCalories(chief.getSalad());

you don't need to have realisation here

2020-11-03 21:35 UTC, AliceIgorevna commented on src/main/java/calculatorCalories/Chief.java
> +    protected Cucumbers cucumbers;
I would say, that easiest way would be having smth like:
 public Vegetable[] salad;
 public int sizeOfTheArray; - as a measure to increase/decrease your salad array. This would lead you to simple implementation of sorting methods (using simple bubble sort or so) + as a methods input parameter you can use varargs
or, alternatively you can proceed with usage of collection, but you still don't need have all concrete vegetables as state of Chief class

2020-11-03 21:35 UTC, AliceIgorevna commented on src/main/java/calculatorCalories/Chief.java
> +    public Chief (Tomato tomato, Pepper pepper, Onion onion, Cucumbers cucumbers){
this is not logical to pass as a constructor parameters to CHIEF object any vegetables, it doesn't makes any sense

2020-11-05 00:20 UTC, YehorKorotun commented on src/main/java/calculatorCalories/Vegetable.java
> +        if (weight != other.weight){return false;}
I would say so, but in the existing menu already indicated how many weight are required.

2020-11-05 00:21 UTC, YehorKorotun commented on src/main/java/calculatorCalories/Vegetable.java
> +public class Vegetable {
thanks

2020-11-05 00:23 UTC, YehorKorotun commented on src/main/java/calculatorCalories/Tomato.java
> +    }
You need to change it in the code) But as I said earlier, we already have a certain weight in the menu.

2020-11-05 00:24 UTC, YehorKorotun commented on src/main/java/calculatorCalories/Pepper.java
> +    }
I left a comment above

2020-11-05 00:24 UTC, YehorKorotun commented on src/main/java/calculatorCalories/Onion.java
> +    }
I left a comment above

2020-11-05 00:24 UTC, YehorKorotun commented on src/main/java/calculatorCalories/Cucumbers.java
> +    }
I left a comment above

2020-11-05 00:25 UTC, YehorKorotun commented on src/main/java/calculatorCalories/Chief.java
> +//    }
got it

2020-11-05 00:27 UTC, YehorKorotun commented on src/main/java/calculatorCalories/Chief.java
> +    public Chief (Tomato tomato, Pepper pepper, Onion onion, Cucumbers cucumbers){
deleted

2020-11-05 00:28 UTC, YehorKorotun commented on src/main/java/calculatorCalories/Chief.java
> +    protected Cucumbers cucumbers;
I try to implement it, thanks

2020-11-15 15:45 UTC, AliceIgorevna approved these changes
generally approved, but need small corrections

2020-11-15 15:45 UTC, AliceIgorevna commented on src/main/java/calculatorCalories/CalculatingCalories.java
> +        }
try to apply java 8 features here

2020-11-15 15:45 UTC, AliceIgorevna commented on src/main/java/calculatorCalories/Chief.java
> +        System.out.println("Start to find vegetable by color...");
'start to find' o_0

2020-11-15 15:45 UTC, AliceIgorevna commented on src/main/java/calculatorCalories/Chief.java
> +                resultOfFind = pair.getKey().toString();
if I would havemore than one vegetable with same colour? I would receive only first available?

2020-11-16 21:17 UTC, YehorKorotun commented on src/main/java/calculatorCalories/Chief.java
> +        System.out.println("Start to find vegetable by color...");
modified

2020-11-16 21:44 UTC, YehorKorotun commented on src/main/java/calculatorCalories/Chief.java
> +                resultOfFind = pair.getKey().toString();
exactly, but we don't have similar colour in our menu)

2020-11-16 21:45 UTC, merged