AT-4 Merge to master
YehorKorotun/Task2 pull request #3
Opened 2020-11-02 14:21 UTC by YehorKorotun

2020-11-03 22:20 UTC, AliceIgorevna requested changes
Format your code, please. Sometimes it is quite difficult to read.
Implement Demo class in order to demonstrate all your work.
_Tip: write more self-descriptive commit messages_

2020-11-03 22:20 UTC, AliceIgorevna commented on src/main/java/menWomenTaskExtended/Human.java
> +    public boolean isSpeak(boolean men, boolean women){
isSpeak? `speak` would be better

2020-11-03 22:20 UTC, AliceIgorevna commented on src/main/java/menWomenTaskExtended/Human.java
> +    public Human isBeInRelationship(Men men, Women women) {
is be? :)

2020-11-03 22:20 UTC, AliceIgorevna commented on src/main/java/menWomenTaskExtended/Human.java
> +        return false;
this method should take only 1 argument, first column of the task represent the object itself, so `this` should be used

2020-11-03 22:20 UTC, AliceIgorevna commented on src/main/java/menWomenTaskExtended/Human.java
> +    public boolean isEndureSociety(boolean men, boolean women){
same for input parameter here

2020-11-03 22:20 UTC, AliceIgorevna commented on src/main/java/menWomenTaskExtended/Human.java
> +    public boolean spendTimeTogether(Men men, Women women){
same

2020-11-03 22:20 UTC, AliceIgorevna commented on src/main/java/menWomenTaskExtended/Human.java
> +    public Human isBeInRelationship(Men men, Women women) {
also mismatch with input parameters, that's why I would not check the implementations, it makes no sense

2020-11-03 22:20 UTC, AliceIgorevna commented on src/main/java/menWomenTaskExtended/Human.java
> +    public Human compatibilityTest(Men men, Women women){
same - one input parameter + `this` for current object

2020-11-03 22:20 UTC, AliceIgorevna commented on src/main/java/menWomenTaskExtended/Women.java
> +        if (human == men | human == women){
why do you need bitwise or here? what do you want to achieve?

2020-11-03 22:20 UTC, AliceIgorevna commented on src/main/java/menWomenTaskExtended/Women.java
> +        }
so in case if user would fill name with emptiness you would throw error and what? your Human would never have name? Maybe you can loop this condition until 100% sure that name filled?

2020-11-03 22:20 UTC, AliceIgorevna commented on src/main/java/menWomenTaskExtended/Women.java
> +        if (human == men | human == women){
and what about comparison of reference data types with `==`? 
for more info read read this: [link](https://medium.com/better-programming/equality-and-comparison-in-java-pitfalls-and-best-practices-96b713e7009) -> Equality section

2020-11-03 22:20 UTC, AliceIgorevna commented on src/main/java/menWomenTaskExtended/DemoClass.java
> +    }
demo should be more representative

2020-11-05 00:30 UTC, YehorKorotun commented on src/main/java/menWomenTaskExtended/Human.java
> +    public boolean isSpeak(boolean men, boolean women){
Modified

2020-11-05 00:35 UTC, YehorKorotun commented on src/main/java/menWomenTaskExtended/Human.java
> +    public Human isBeInRelationship(Men men, Women women) {
modified

2020-11-05 09:12 UTC, YehorKorotun commented on src/main/java/menWomenTaskExtended/Women.java
> +        if (human == men | human == women){
In this case human == men | human == women, I wanted to select a gender of child, but I don't know how to implement it((((((

2020-11-05 09:13 UTC, YehorKorotun commented on src/main/java/menWomenTaskExtended/Women.java
> +        if (human == men | human == women){
You are right, I must use equals()

2020-11-05 09:14 UTC, YehorKorotun commented on src/main/java/menWomenTaskExtended/Women.java
> +        }
I try to implement it

2020-11-05 09:15 UTC, YehorKorotun commented on src/main/java/menWomenTaskExtended/DemoClass.java
> +    }
Sure, it looks like that because I don't have a full functionality

2020-12-01 12:03 UTC, merged