AT-5 Merge to master enumTask.package
YehorKorotun/Task2 pull request #4
Opened 2020-11-04 23:51 UTC by YehorKorotun

2020-11-11 20:42 UTC, AliceIgorevna requested changes
generally - good work 👍  you're doing well. please, pay attention to comments

2020-11-11 20:42 UTC, AliceIgorevna commented on src/main/java/enumTask/StudentInformation.java
> +    public void resultOfCourse(WorkProgram workProgram, long durationTime) throws ParseException {
handle exception inside of this method

2020-11-11 20:42 UTC, AliceIgorevna commented on src/main/java/enumTask/StudentInformation.java
> +    public void resultOfCourse(WorkProgram workProgram, long durationTime) throws ParseException {
distinguish this method to 2 methods - one should return boolean in case if student finished course, another is gathering info regarding course longevity and info regarding finishing (рассчитать, сколько дней и часов  осталось студенту до окончания программы или сколько дней и часов назад студент закончил изучение программы обучения.) this part

2020-11-11 20:42 UTC, AliceIgorevna commented on src/main/java/enumTask/WorkProgram.java
> +    public WorkProgram(String courseName, String dateStart) {
date should be not a String type

2020-11-11 20:42 UTC, AliceIgorevna commented on src/main/java/enumTask/WorkProgram.java
> +    public Date getStartDate() throws ParseException {
exception should be handled here

2020-11-11 20:42 UTC, AliceIgorevna commented on src/main/java/enumTask/WorkProgram.java
> +    public Date getStartDate() throws ParseException {
in case if date did not corresponds to expected, program should terminate here

2020-11-11 20:42 UTC, AliceIgorevna commented on src/main/java/enumTask/WorkProgram.java
> +    public StringBuilder getEndDateOfCourse(long timeToScore) {
better to return date, for example for future manipulations with it

2020-11-11 20:42 UTC, AliceIgorevna commented on src/main/java/enumTask/WorkProgram.java
> +        return endDate;
can be inlined

2020-11-11 20:42 UTC, AliceIgorevna commented on src/main/java/enumTask/WorkProgram.java
> +        return dateFormat;
can be inlined

2020-11-11 20:42 UTC, AliceIgorevna commented on src/main/java/enumTask/WorkProgram.java
> +        return TIME_END;
this belongs to an working hours, method names are incorrect

2020-11-13 14:31 UTC, YehorKorotun commented on src/main/java/enumTask/StudentInformation.java
> +    public void resultOfCourse(WorkProgram workProgram, long durationTime) throws ParseException {
Add

2020-11-13 14:34 UTC, YehorKorotun commented on src/main/java/enumTask/StudentInformation.java
> +    public void resultOfCourse(WorkProgram workProgram, long durationTime) throws ParseException {
Sorry, I don't got it)

2020-11-13 14:39 UTC, YehorKorotun commented on src/main/java/enumTask/WorkProgram.java
> +    public WorkProgram(String courseName, String dateStart) {
Modified

2020-11-13 14:40 UTC, YehorKorotun commented on src/main/java/enumTask/WorkProgram.java
> +        return TIME_END;
Modified

2020-12-01 12:04 UTC, merged