AT-9 Modified MathOperations.java, add MathOperationsTest.java, created tests.
YehorKorotun/Task2 pull request #8
Opened 2020-11-10 10:14 UTC by YehorKorotun

2020-11-15 15:34 UTC, AliceIgorevna requested changes

2020-11-15 15:34 UTC, AliceIgorevna commented on src/test/java/customException/MathOperationsTest.java
> +        Assert.assertEquals(13, mathOperations.sum(5, 8));
why such input values were selected? base on which test design technique?

2020-11-15 15:34 UTC, AliceIgorevna commented on src/test/java/customException/MathOperationsTest.java
> +        Assert.assertEquals(5, mathOperations.subtraction(10, 5));
same

2020-11-15 15:34 UTC, AliceIgorevna commented on src/test/java/customException/MathOperationsTest.java
> +        Assert.assertEquals(20, mathOperations.multiplication(10, 2));
same

2020-11-15 15:34 UTC, AliceIgorevna commented on src/test/java/customException/MathOperationsTest.java
> +        }
what this test is verifying?

2020-11-16 22:57 UTC, YehorKorotun commented on src/test/java/customException/MathOperationsTest.java
> +        Assert.assertEquals(13, mathOperations.sum(5, 8));
modified

2020-11-16 22:58 UTC, YehorKorotun commented on src/test/java/customException/MathOperationsTest.java
> +        }
modified

2020-12-01 12:16 UTC, merged